version: "3"
services:
    webapplication3:
        build: 
          context: .
          dockerfile: Dockerfile
        ports:
            - "8080:80"
        depends_on:
            - mongo
            - redis
    mongo:
        image: mongo
        ports:
            - "27017:27017"

    redis:
        image: redis
        ports:
            - "6379:6379"